"use server";
/**
 * lib/orders/actions.ts — Server Actions for the Orders module
 */
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { requireRole } from "@/lib/auth/session";
import { checkOrderDuplicate } from "./duplicate";
import type { OrderStatus } from "@/types/orders";
import { AGENT_ALLOWED_STATUSES } from "@/types/orders";

const MANAGER_ROLES = ["super_admin", "admin", "manager"] as const;
const ALL_ORDER_ROLES = ["super_admin", "admin", "manager", "call_center_agent"] as const;

// ─── Create order ──────────────────────────────────────────────────────────────
export async function createOrder(formData: FormData) {
  const session = await requireRole([...MANAGER_ROLES]);
  const supabase = await createClient();

  // Validate
  const customerName  = String(formData.get("customer_name") ?? "").trim();
  const customerPhone = String(formData.get("customer_phone") ?? "").trim();
  const customerCity  = String(formData.get("customer_city") ?? "").trim();
  const customerAddr  = String(formData.get("customer_address") ?? "").trim();
  const productId     = String(formData.get("product_id") ?? "").trim();
  const qty           = parseInt(String(formData.get("quantity") ?? "1"));
  const source        = String(formData.get("source") ?? "manual").trim();
  const notes         = String(formData.get("notes") ?? "").trim() || null;
  const shippingCharge = parseFloat(String(formData.get("shipping_charge") ?? "0")) || 0;
  const assignedTo    = String(formData.get("assigned_to") ?? "").trim() || null;

  const errors: Record<string, string> = {};
  if (!customerName)  errors.customer_name  = "Nom requis.";
  if (!customerPhone) errors.customer_phone = "Téléphone requis.";
  if (!customerCity)  errors.customer_city  = "Ville requise.";
  if (!productId)     errors.product_id     = "Produit requis.";
  if (isNaN(qty) || qty < 1) errors.quantity = "Quantité invalide.";

  if (Object.keys(errors).length > 0) return { success: false, errors };

  // Fetch product for pricing snapshot
  const { data: product, error: pErr } = await supabase
    .from("products")
    .select("id, name, sku, sale_price_mad, total_cost_mad")
    .eq("id", productId)
    .single();

  if (pErr || !product) {
    return { success: false, errors: { product_id: "Produit introuvable." } };
  }

  const p = product as unknown as {
    id: string; name: string; sku: string;
    sale_price_mad: number; total_cost_mad: number;
  };

  const unitPrice   = p.sale_price_mad ?? 0;
  const unitCost    = p.total_cost_mad ?? 0;
  const subtotal    = unitPrice * qty;
  const cogs        = unitCost * qty;
  const estProfit   = subtotal + shippingCharge - cogs;

  // Check for duplicate (same phone + same product + last 24h)
  const dupCheck = await checkOrderDuplicate(customerPhone, productId);

  // Insert order (order_number auto-generated by trigger)
  const { data: order, error: oErr } = await supabase
    .from("orders")
    .insert({
      customer_name:    customerName,
      customer_phone:   customerPhone,
      customer_city:    customerCity,
      customer_address: customerAddr || customerCity,
      status:           "new",
      subtotal,
      shipping_charge:  shippingCharge,
      discount_amount:  0,
      cogs_total:       cogs,
      estimated_profit: estProfit,
      assigned_to:      assignedTo,
      source,
      notes,
      import_source:    "manual",
      is_duplicate:     dupCheck.isDuplicate,
      duplicate_of:     dupCheck.existingOrderId,
    } as never)
    .select("id, order_number")
    .single();

  if (oErr || !order) {
    return { success: false, errors: { _form: oErr?.message ?? "Erreur création commande." } };
  }

  const orderId = (order as { id: string }).id;

  // Insert order item
  const { error: iErr } = await supabase
    .from("order_items")
    .insert({
      order_id:     orderId,
      product_id:   p.id,
      product_name: p.name,
      product_sku:  p.sku,
      unit_price:   unitPrice,
      unit_cost_mad:unitCost,
      quantity:     qty,
      discount_pct: 0,
    } as never);

  if (iErr) {
    // Rollback order if items fail
    await supabase.from("orders").delete().eq("id", orderId);
    return { success: false, errors: { _form: iErr.message } };
  }

  // Log status history
  await supabase.from("order_status_history").insert({
    order_id:   orderId,
    from_status: null,
    to_status:  "new",
    changed_by: session.authId,
    notes:      "Commande créée manuellement.",
  } as never);

  revalidatePath("/admin/orders");
  return { success: true, orderId, orderNumber: (order as { order_number: string }).order_number, isDuplicate: dupCheck.isDuplicate, duplicateOfNumber: dupCheck.existingOrderNumber };
}

// ─── Update order status ───────────────────────────────────────────────────────
export async function updateOrderStatus(
  orderId: string,
  newStatus: OrderStatus,
  statusNote?: string
) {
  const session = await requireRole([...ALL_ORDER_ROLES]);
  const supabase = await createClient();

  // Agents can only set allowed statuses
  if (session.role === "call_center_agent") {
    if (!AGENT_ALLOWED_STATUSES.includes(newStatus)) {
      return { success: false, error: "Statut non autorisé pour votre rôle." };
    }
    // Agent can only update their assigned orders
    const { data: order } = await supabase
      .from("orders")
      .select("id, status, assigned_to")
      .eq("id", orderId)
      .single();
    const o = order as { id: string; status: string; assigned_to: string | null } | null;
    if (!o || o.assigned_to !== session.authId) {
      return { success: false, error: "Commande non assignée à vous." };
    }
  }

  // Get current status for history
  const { data: current } = await supabase
    .from("orders")
    .select("status")
    .eq("id", orderId)
    .single();
  const currentStatus = (current as { status: string } | null)?.status ?? null;

  // Update
  const updatePayload: Record<string, unknown> = { status: newStatus };
  if (newStatus === "confirmed") {
    updatePayload.confirmed_by = session.authId;
    updatePayload.confirmed_at = new Date().toISOString();
  }

  const { error } = await supabase
    .from("orders")
    .update(updatePayload as never)
    .eq("id", orderId);

  if (error) return { success: false, error: error.message };

  // Log history
  await supabase.from("order_status_history").insert({
    order_id:    orderId,
    from_status: currentStatus,
    to_status:   newStatus,
    changed_by:  session.authId,
    notes:       statusNote ?? null,
  } as never);

  revalidatePath(`/admin/orders/${orderId}`);
  revalidatePath("/admin/orders");
  return { success: true };
}

// ─── Assign agent ──────────────────────────────────────────────────────────────
export async function assignOrderAgent(orderId: string, agentId: string | null) {
  await requireRole([...MANAGER_ROLES]);
  const supabase = await createClient();

  const { error } = await supabase
    .from("orders")
    .update({ assigned_to: agentId } as never)
    .eq("id", orderId);

  if (error) return { success: false, error: error.message };

  revalidatePath(`/admin/orders/${orderId}`);
  revalidatePath("/admin/orders");
  return { success: true };
}

// ─── Update tracking number ────────────────────────────────────────────────────
export async function updateTrackingNumber(orderId: string, tracking: string) {
  await requireRole([...MANAGER_ROLES]);
  const supabase = await createClient();

  const { error } = await supabase
    .from("orders")
    .update({ delivery_tracking_number: tracking || null } as never)
    .eq("id", orderId);

  if (error) return { success: false, error: error.message };

  revalidatePath(`/admin/orders/${orderId}`);
  return { success: true };
}

// ─── Update notes ──────────────────────────────────────────────────────────────
export async function updateOrderNotes(orderId: string, notes: string) {
  await requireRole([...ALL_ORDER_ROLES]);
  const supabase = await createClient();

  const { error } = await supabase
    .from("orders")
    .update({ notes: notes || null } as never)
    .eq("id", orderId);

  if (error) return { success: false, error: error.message };

  revalidatePath(`/admin/orders/${orderId}`);
  return { success: true };
}

// ─── Delete order ──────────────────────────────────────────────────────────────
export async function deleteOrder(orderId: string) {
  await requireRole([...MANAGER_ROLES]);
  const supabase = await createClient();

  const { error } = await supabase.from("orders").delete().eq("id", orderId);
  if (error) return { success: false, error: error.message };

  revalidatePath("/admin/orders");
  redirect("/admin/orders");
}
